# =====================
# Build
# =====================
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet publish app-blazor/app-blazor.csproj -c Release -o /app

# =====================
# Runtime
# =====================
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app ./

EXPOSE 5099
ENTRYPOINT ["dotnet", "app-blazor.dll"]
