# =====================
# Build Stage
# =====================
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet publish app-web/app-web.csproj -c Release -o /app

# =====================
# Runtime Stage
# =====================
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app ./

EXPOSE 5174
ENTRYPOINT ["dotnet", "app-web.dll"]
